### ISSUE TITLE
Attribute error in scripts/reconstruct_dataset.py

### ISSUE THREAD

**Issue by Haelles** [jifan-chen/subquestions-for-fact-checking#1]
Dear author,
        Thanks for your great work. However, I met a bug when preprocessing the dataset. I use 'bash scripts/download_data.sh' and got "AttributeError: NoneType object has no attribute 'get text'" in line 58`time_venue = time_venue.get_text(strip=True)`. Could you please have a look at the data?

**Comment by jifan-chen** [comment]
I think it's likely the original URL is broken. Can you send me an email and I can just send you the data
