### ISSUE TITLE
Question generation training code doesn't work. requirements is incomplete, missing modules etc. Is the fine-tuned T5-3B model shared somewhere?

### ISSUE THREAD

**Issue by vinaysetty** [jifan-chen/subquestions-for-fact-checking#3]

**Comment by jifan-chen** [comment]
Actually, you can achieve much better performance using few-shot prompting with some of more recent LLMs. That's why I didn't bother to add the T5-3B model. If you want the checkpoint, I can share

**Comment by vinaysetty** [comment]
Thanks, I know few-shot would perform better with larger LLMs. But I am interested on how smaller models would perform. Anyway I managed to fix a few things in the code and trained the model https://huggingface.co/Factiverse/T5-3B-ClaimDecomp.
